version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
      - redis
    environment:
      - NODE_ENV={NODE_ENV}
  mysql:
    image: mysql:8.0
    ports:
      - '3307:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
  redis:
    image: redis:6
    ports:
      - '6380:6379'
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes
